### ISSUE TITLE
数据转换

### ISSUE THREAD

**Issue by BetterOne-yzh** [Ascend/modelzoo#1]
你好，yolov5 acl模型的输入为temp_buffer_size为2,457,600的3*640*640的两倍，这个不会有影响吗？在c++里该怎么实现这个呢？

**Comment by ascendhuawei** [comment]
Hi, 
Your question is not very clear by 'yolov5 acl模型的输入为temp_buffer_size为2,457,600的3640640的两倍'. 
Please give more backgrounds.

**Comment by BetterOne-yzh** [comment]
我模型的输入为FP16，图像为float，该怎么处理啊，有相关的教程吗？

**Comment by ascendhuawei** [comment]
Please check on this API
https://support.huaweicloud.com/aclcppdevg-cann505alpha1/aclcppdevg_api_04_0495.html
